architectCabinet = document.getElementById("architectCabinet");
banditCamp = document.getElementById("banditCamp");
banditFort = document.getElementById("banditFort");
banditRedoubt = document.getElementById("banditRedoubt");
blackMarket = document.getElementById("blackMarket");
brotherhood = document.getElementById("brotherhood");
buildersUnion = document.getElementById("buildersUnion");
cells = document.getElementById("cells");
cenotaph = document.getElementById("cenotaph");
clandestineDockEastWest = document.getElementById("clandestineDockEastWest");
consulate = document.getElementById("consulate");
contingen = document.getElementById("contingen");
counterfeitersOffice = document.getElementById("counterfeitersOffice");
customs = document.getElementById("customs");
embassy = document.getElementById("embassy");
gambelingDen = document.getElementById("gambelingDen");
gambelingHouse = document.getElementById("gambelingHouse");
hideout = document.getElementById("hideout");
jailYard = document.getElementById("jailYard");
lair = document.getElementById("lair");
memorial = document.getElementById("memorial");
mercenaries = document.getElementById("mercenaries");
militia = document.getElementById("militia");
opiumCache = document.getElementById("opiumCache");
opiumDen = document.getElementById("opiumDen");
opiumRefinery = document.getElementById("opiumRefinery");
pigeionLoft = document.getElementById("pigeionLoft");
prison = document.getElementById("prison");
residence = document.getElementById("residence");
secretWarehouse = document.getElementById("secretWarehouse");
sepulcher = document.getElementById("sepulcher");
smugglersCache = document.getElementById("smugglersCache");
spyRing = document.getElementById("spyRing");
stockExchange = document.getElementById("stockExchange");
stockMarket = document.getElementById("stockMarket");
tortureChamber = document.getElementById("tortureChamber");


architectCabinetText = "ARCHITECT CABINET \nStarting from the moment the Architect Cabinet enters play, a player can build his or her Wonder stages without having to pay their resource costs.\n\nClarification: The cost in coins for some Wonder stages must still be paid, however (Petra).";
banditCampText ="BANDIT CAMP \nThis card grant the player one Military Victory token (from Age I). Each of the player's neighbors takes a -1 Debt token.";
banditFortText ="BANDIT FORT \nThis card grant the player one Military Victory token (from Age III). Each of the player's neighbors takes a -1 Debt token.";
banditRedoubtText ="BANDIT REDOUBT \nThis card grant the player one Military Victory token (from Age II). Each of the player's neighbors takes a -1 Debt token.";
blackMarketText ="BLACK MARKET \nEach turn, the card produces one resource of the player's choice from among those that their city doesn't produce through the use ofits brown and gray cards or the initial resource of their board. \n\nClarification: The resources produced by the yellow, white and black cards aren't taken into account.";
brotherhoodText ="BROTHERHOOD \nThis card earn victory points and cause monetary loss : every other player must pay 3 coins to the bank at the end of the turn in which the card is played.";
buildersUnionText ="BUILDER'S UNION \nThis card is worth 4 Victory Points and every other player must pay 1 coin to the bank for each stage of their Wonder they have built.";
cellsText ="CELLS \nAt the end of the game, this card are worth 2 victory points for each Military Victory token from Age I.";
cenotaphText ="CENOTAPH \nThis card earn victory points and the other players must pay 1 coin to the bank for each Victory Conflict token (no matter its value) in their possession.";
clandestineDockEastWestText ="CLANDESTINE DOCK (EAST / WEST) \nEach turn, the player has a commercial rebate of one coin on the first resource (brown or gray) they buy from the neighboring city (left or right depending on the symbol). This rebate is cumulative with that of a Market or a Counter : the first resource bought can thus be free.";
consulateText ="CONSULATE \nThis card earn victory points and each grants a Diplomacy token.";
contingenText ="CONTINGENT \nThis card offer more shields than the red cards of the corresponding Age (5 Shields).";
counterfeitersOfficeText ="COUNTERFEITER'S OFFICE \nThe player can choose an Age card in the discard pile and put it into play for free. \n\nClarification: If multiple players take cards from the discard pile during a single turn, the resolution order is as follows: Halicarnassus, The Great Wall, Manneken Pis, Solomon, the Counterfeiter's Office, and finally the Courtesans Guild.";
customsText ="CUSTOMS \nThis card are worth victory points to the player. Each other player takes 1 coin from the bank.";
embassyText ="EMBASSY \nThis card earn victory points and each grants a Diplomacy token.";
gambelingDenText ="GAMBLING DEN \nThe player takes 6 coins from the bank. The player's two neighbors each take 1 coin from the bank.";
gambelingHouseText ="GAMBLING HOUSE \nThe player takes 9 coins from the bank. The player's two neighbors each take 2 coins from the bank.";
hideoutText ="HIDEOUT \nThis card earn victory points and cause monetary loss : every other player must pay 1/2/3 coins (respectively) to the bank at theend of the turn in which the card is played.";
jailYardText ="JAIL YARD \nAt the end of the game, this card are worth 3 victory points for each Military Victory token from Age II.";
lairText ="LAIR \nThis card earn victory points and cause monetary loss : every other player must pay 1/2/3 coins (respectively) to the bank at theend of the turn in which the card is played.";
memorialText ="MEMORIAL \nThe player takes 2 coins for each of their Military Defeat tokens, then the player discards all of their Military Defeat tokens.";
mercenariesText ="MERCENARIES \nThis card offer more shields than the red cards of the corresponding Age (3 Shields).";
militiaText ="mMILITIA \nThis card offer more shields than the red cards of the corresponding Age (2 Shields).";
opiumCacheText ="OPIUM CACHE \nThe player takes 3 coins from the bank. Each other player must pay 1 coins to the bank.";
opiumDenText ="OPIUM DEN \nThe player takes 4 coins from the bank. Each other player must pay 3 coins to the bank.";
opiumRefineryText ="OPIUM REFINERY \nThe player takes 5 coins from the bank. Each other player must pay 5 coins to the bank.";
pigeionLoftText ="PIGEON LOFT \nThis card grant a symbol. At the end of the game, each mask allows the controlling player to copy the scientific symbol of a green card present in one of the two neighboring cities.";
prisonText ="PRISON \nAt the end of the game, this card are worth 3 VP for each Military Victory token from Age III.";
residenceText ="RESIDENCE \nThis card earn VP and each grants aDiplomacy token.";
secretWarehouseText ="SECRET WAREHOUSE \nEach turn, the card produces a resource of the player's choice from among those that their city already produces through its brown and gray cards or the initial resource of their board. \n\nClarification: the Secret Warehouse doesn't allow players to double the production on yellow, white, or black cards (Forum, Caravansary, Bilkis and Black Market).";
sepulcherText ="SEPULCHER \nThis card earn victory points and the other players must pay 1 coin to the bank for each Victory Conflict token (no matter its value) in their possession.";
smugglersCacheText ="SMUGGLER'S CACHE \nThe player has a commercial rebate of 1 coin on the resources (brown or grey) produced by the Wonder boards of the two neighboring cities.";
spyRingText ="SPY RING \nThis card grant a  symbol. At the end of the game, each mask allows the controlling player to copy the scientific symbol of a green card present in one of the two neighboring cities.";
stockExchangeText ="STOCK EXCHANGE \nThis card are worth victory points to the player. Each other player takes 3 coins from the bank.";
stockMarketText ="STOCK MARKET \nThis card are worth victory points to the player. Each other player takes 2 coins from the bank.";
tortureChamberText ="TORTURE CHAMBER \nThis card grant a symbol. At the end of the game, each mask allows the controlling player to copy the scientific symbol of a green card present in one of the two neighboringcities.";

architectCabinet.addEventListener("click", function(){ alert(architectCabinetText); });
banditCamp.addEventListener("click", function(){ alert(banditCampText); });
banditFort.addEventListener("click", function(){ alert(banditFortText); });
banditRedoubt.addEventListener("click", function(){ alert(banditRedoubtText); });
blackMarket.addEventListener("click", function(){ alert(blackMarketText); });
brotherhood.addEventListener("click", function(){ alert(brotherhoodText); });
buildersUnion.addEventListener("click", function(){ alert(buildersUnionText); });
cells.addEventListener("click", function(){ alert(cellsText); });
cenotaph.addEventListener("click", function(){ alert(cenotaphText); });
clandestineDockEastWest.addEventListener("click", function(){ alert(clandestineDockEastWestText); });
consulate.addEventListener("click", function(){ alert(consulateText); });
contingen.addEventListener("click", function(){ alert(contingenText); });
counterfeitersOffice.addEventListener("click", function(){ alert(counterfeitersOfficeText); });
customs.addEventListener("click", function(){ alert(customsText); });
embassy.addEventListener("click", function(){ alert(embassyText); });
gambelingDen.addEventListener("click", function(){ alert(gambelingDenText); });
gambelingHouse.addEventListener("click", function(){ alert(gambelingHouseText); });
hideout.addEventListener("click", function(){ alert(hideoutText); });
jailYard.addEventListener("click", function(){ alert(jailYardText); });
lair.addEventListener("click", function(){ alert(lairText); });
memorial.addEventListener("click", function(){ alert(memorialText); });
mercenaries.addEventListener("click", function(){ alert(mercenariesText); });
militia.addEventListener("click", function(){ alert(militiaText); });
opiumCache.addEventListener("click", function(){ alert(opiumCacheText); });
opiumDen.addEventListener("click", function(){ alert(opiumDenText); });
opiumRefinery.addEventListener("click", function(){ alert(opiumRefineryText); });
pigeionLoft.addEventListener("click", function(){ alert(pigeionLoftText); });
prison.addEventListener("click", function(){ alert(prisonText); });
residence.addEventListener("click", function(){ alert(residenceText); });
secretWarehouse.addEventListener("click", function(){ alert(secretWarehouseText); });
sepulcher.addEventListener("click", function(){ alert(sepulcherText); });
smugglersCache.addEventListener("click", function(){ alert(smugglersCacheText); });
spyRing.addEventListener("click", function(){ alert(spyRingText); });
stockExchange.addEventListener("click", function(){ alert(stockExchangeText); });
stockMarket.addEventListener("click", function(){ alert(stockMarketText); });
tortureChamber.addEventListener("click", function(){ alert(tortureChamberText); });