amytis = document.getElementById("amytis");
alexander = document.getElementById("alexander");
archimedes = document.getElementById("archimedes");
aristotle = document.getElementById("aristotle");
aspasia = document.getElementById("aspasia");
berenice = document.getElementById("berenice");
bilkis = document.getElementById("bilkis");
caesar = document.getElementById("caesar");
caligula = document.getElementById("caligula");
cleopatra = document.getElementById("cleopatra");
croesus = document.getElementById("croesus");
darius = document.getElementById("darius");
diocletian = document.getElementById("diocletian");
euclid = document.getElementById("euclid");
hammurabi = document.getElementById("hammurabi");
hannibal = document.getElementById("hannibal");
hatshepsut = document.getElementById("hatshepsut");
hiram = document.getElementById("hiram");
hypatia = document.getElementById("hypatia");
imhotep = document.getElementById("imhotep");
justinian = document.getElementById("justinian");
leonidas = document.getElementById("leonidas");
maecenas = document.getElementById("maecenas");
midas = document.getElementById("midas");
nebuckadnezzar = document.getElementById("nebuckadnezzar");
nefertiti = document.getElementById("nefertiti");
nero = document.getElementById("nero");
pericles = document.getElementById("pericles");
phidias = document.getElementById("phidias");
plato = document.getElementById("plato");
praxiteles = document.getElementById("praxiteles");
ptolemy = document.getElementById("ptolemy");
pythagoras = document.getElementById("pythagoras");
ramses = document.getElementById("ramses");
salomo = document.getElementById("salomo");
sappho = document.getElementById("sappho");
semiramis = document.getElementById("semiramis");
tomyris = document.getElementById("tomyris");
varro = document.getElementById("varro");
vitruvius = document.getElementById("vitruvius");
xenophon = document.getElementById("xenophon");
zenobia = document.getElementById("zenobia");

aganice = document.getElementById("aganice");
agrippina = document.getElementById("agrippina");
arsinoe = document.getElementById("arsinoe");
cornelia = document.getElementById("cornelia");
cynisca = document.getElementById("cynisca");
enheduanna = document.getElementById("enheduanna");
eurypyle = document.getElementById("eurypyle");
gorgo = document.getElementById("gorgo");
makeda = document.getElementById("makeda");
nitocris = document.getElementById("nitocris");
octavia = document.getElementById("octavia");
phryne = document.getElementById("phryne");
roxana = document.getElementById("roxana");
telesilla = document.getElementById("telesilla");
theano = document.getElementById("theano");


amytisText = "AMYTIS \nVid spelets slut är Amytil värd 2VP för varje underverksnivå byggd av spelaren.";
alexanderText ="ALEXANDER \nVid spelets slut lägger Alexander till 1 VP på varje konfliktvinstmarkör (värdet på konfliktvinstmarkörerna går därför från 1, 3 och 5 VP till 2, 4, och 6VP).";
archimedesText ="ARCHIMEDES \nSå fort Archimedes rekryteras tillåter de att spelaren betalar en resurs mindre än angiven kostnad för konstruerandet av byggnader i grön färg. \n\nFörtydligande: Vilken resurs som spelaren inte behöver betala väljer spelaren själv. Det kan vara en råvara (brun) eller ett tillverkande gods (grå).";
aristotleText ="ARISTOTLE \nVid spelets slut lägger Aristoteles till 3 VP till varje grupp av olika vetenskapssymboler (detta innebär att bonuspoängen går från 7 VP till 10 VP per grupp).";
aspasiaText ="ASPASIA \nWhen Aspasia enters play, the player takes a Diplomacy token. (Asasia is also worth 2 victory points at the end of the game).";
bereniceText ="BERENICE \nFrom the moment she enters play, each amount of coins taken from the bank is increased by 1. This increase is limited to one coin per turn. Example: discarding a card earns 4 coins, a tavern 6,.. \n\nClarification: coins given by neighbors through the purchase of resources isn't considered coming from the bank.";
bilkisText ="BILKIS \nNär Bilkis rekryteras tillåter hon att spelaren får köpa valfri resurs genom att betala 1 mynt till bankenen gång per omgång.";
caesarText ="CAESAR \nNär Caesar rekryteras innebär de angivet antal extra sköldar.";
caligulaText ="CALIGULA \nThe player can build one black card per Age for free.";
cleopatraText ="CLEOPATRA \nVid spelets slut är Cleopatra värd 5 VP.";
croesusText ="CROESUS \nSå fort han rekryteras ger han omedelbart spelaren 6 mynt som tas från banken.";
dariusText ="DARIUS \nEach black card is worth 1 VP at the end of the game.";
diocletianText ="DIOCLETIAN \nFrom the moment he enters play, Diocletian earns 2 coins for each black card that the player builds.";
euclidText ="EUCLID \nEuclid innebär en extra vetenskapssymbol vilken finns angiver på kortet. Denna symbol läggs till de som återfinns på vetenskapliga byggnaderna (gröna kort) I spelarens stad.";
hammurabiText ="HAMMURABI  \nSå fort Hammurabi rekryteras tillåter de att spelaren betalar en resurs mindre än angiven kostnad för konstruerandet av byggnader I blå färg.\n\nFörtydligande: Vilken resurs som spelaren inte behöver betala väljer spelaren själv. Det kan vara en råvara (brun) eller ett tillverkande gods (grå).";
hannibalText ="HANNIBAL \nNär Hannibal rekryteras innebär de angivet antal extra sköldar.";
hatshepsutText ="HATSHEPSUT \nNär hon rekryteras ger varje köp av resurser från grannarna 1 mynt från banken. Notera att denna ynnerst är begränsad till 1 mynt per granne per omgång.Förtydligande: spelaren tar mynt från banken omdelebart EFTER genomförd betalning.";
hiramText ="HIRAM \nVid spelets slut är Hiram värd 2 VP för varje lila kort I spelarens stad.";
hypatiaText ="HYPATIA \nVid spelets slut är Hypatia värd 1 VP för varje grönt kort I spelarens stad.";
imhotepText ="IMHOTEP \nSå fort Imhotep rekryteras tillåter de att spelaren betalar en resurs mindre än angiven kostnad för konstruerandet av Underverksnivåer.\n\nFörtydligande: Vilken resurs som spelaren inte behöver betala väljer spelaren själv. Det kan vara en råvara (brun) eller ett tillverkande gods (grå).";
justinianText ="JUSTINIAN \nVid spelets slut är Justinian värd 3 VP för varje grupp av 3 tidsålderskort (röd, blå, grön).";
leonidasText ="LEONIDAS \nSå fort Leonidas rekryteras tillåter de att spelaren betalar en resurs mindre än angiven kostnad för konstruerandet av byggnader I röd färg. \n\nFörtydligande: Vilken resurs som spelaren inte behöver betala väljer spelaren själv. Det kan vara en råvara (brun) eller ett tillverkande gods (grå).";
maecenasText ="MAECENAS \nNär Maecenas rekryteras kan spelaren rekrytera samtliga framtida ledare gratis (under Rekryteringsfasen) utan att behöva betala myntkostnaden.";
midasText ="MIDAS \nVid spelets slut är Midas värd 1 VP för var tredje mynt i spelarens ägo. \n\nFörtydligande: Dessa poäng läggs till de som normalt ges för mynt (spelaren får därför 2 VP för var tredje mynt).";
nebuckadnezzaText ="NEBUCHADNEZZAR \nVid spelets slut är Nebuckadnezzar värd 1 VP för varje blått kort I spelarens stad.";
nefertitiText ="NEFERTITI \nVid spelets slut är Nefertiti värd 4 VP.";
neroText ="NERO \nNär han rekryteras ger Nero 2 mynt för varje militär vinst spelaren får uppleva. Dessa mynt tas från banken när de Millitära Vinstmarkörerna delas ut.\n\nFörtydligande: Nero har påverkar inte de Millitära vinstmarkörerna som erhållits innan ha rekryterades.";
periclesText ="PERICLES \nVid spelets slut är Pericles värd 2 VP för varje rött kort i spelarens stad.";
phidiasText ="PHIDIAS \nVid spelets slut är Phidias värd 1 VP för varje brunt kort i spelarens stad.";
platoText ="PLATO \nVid spelets slut är Plato värd 7 VP för varje grupp med 7 tidsålderskort (brun, grå, grön, blå, gul, röd, lila).";
praxitelesText ="PRAXITELES \nVid spelets slut är Praxiteles värd 2 VP för varje grått kort I spelarens stad.";
ptolemyText ="PTOLEMY \nPtolemy innebär en extra vetenskapssymbol vilken finns angiver på kortet. Denna symbol läggs till de som återfinns på vetenskapliga byggnaderna (gröna kort) i spelarens stad.";
pythagorasText ="PYTHAGORAS \nPythagoras innebär en extra vetenskapssymbol vilken finns angiver på kortet. Denna symbol läggs till de som återfinns på vetenskapliga byggnaderna (gröna kort) i spelarens stad.";
ramsesText ="RAMSES \nNär Ramses rekryteras kan spelaren bygga alla sina Skrån gratis, utan att behöva betala några resurskostnader.";
salomoText ="SALOMO \nSå fort Salomo rekryteras kan spelaren välja ett tidsålderskort från slänghögen och spela ut det gratis.";
sapphoText ="SAPPHO \nVid spelets slut är Sappho värd 2 VP.";
semiramisText ="SEMIRAMIS \nFrom the moment when she enters play, each Defeat Conflict token counts as a Shield symbol for all future conflict phases.(Place your Defeat tokens on the Semiramis card to make it clearer).";
tomyrisText ="TOMYRIS \nNär Tomyris rekryteras får spelaren, under konfliktutredningen, ge de Förlustmarkörer han eller hon tilldelas till den segrande grannen. Notera: Tomyris har ingen effect om spelarens stad går segrande ur en konflikt eller när det gäller konflikter som skett innan Tomyris rekryterades.";
varroText ="VARRO \nVid spelets slut är Varro värd 1 VP för varje gult kort i spelarens stad.";
vitruviusText ="VITRUVIUS \nNär har rekryteras ger Vitruvius 2 mynt för varje gång spelaren bygger en byggnade gratis på grund av befintlig byggnadskedja. Mynten tas från banken samtidigt som byggnaden färdigställs.\n\nFörtydligande: Viruvius påverkar inte byggnader byggda med hjälpa av byggnadskedjan innan han rekryterades.";
xenophonText ="XENOPHON \nNär han rekryteras ger Xenophon 2 mynt för varje kommersiell byggnad (gula kort) som spelaren bygger. Mynten tas från bankensamtidigt som byggnaden färdigställs.\n\nFörtydligande: Xenophon påverkar inte de kommersiella byggnader som byggts innan han rekryterades.";
zenobiaText ="ZENOBIA \nVid spelets slut är Zenobia värd 3 VP.";

aganiceText ="AGANICE \nVid spelets slut är Zenobia värd 3 VP.";
agrippinaText ="AGRIPPINA \nVid spelets slut är Zenobia värd 3 VP.";
arsinoeText ="ARSINOE \nVid spelets slut är Zenobia värd 3 VP.";
corneliaText ="CORNELIA \nVid spelets slut är Zenobia värd 3 VP.";
cyniscaText ="CYNISCA \nVid spelets slut är Zenobia värd 3 VP.";
enheduannaText ="ENHEDUANNA \nVid spelets slut är Zenobia värd 3 VP.";
eurypyleText ="EURYPLE \nVid spelets slut är Zenobia värd 3 VP.";
gorgoText ="GORGO \nVid spelets slut är Zenobia värd 3 VP.";
makedaText ="MAKEDA \nVid spelets slut är Zenobia värd 3 VP.";
nitocrisText ="NITOCRIS \nVid spelets slut är Zenobia värd 3 VP.";
octaviaText ="OCTAVIA \nVid spelets slut är Zenobia värd 3 VP.";
phryneText ="PHRYNE \nVid spelets slut är Zenobia värd 3 VP.";
roxanaText ="Roxana \nVid spelets slut är Zenobia värd 3 VP.";
telesillaText ="TELESILLA \nVid spelets slut är Zenobia värd 3 VP.";
theanoText ="THEANO \nVid spelets slut är Zenobia värd 3 VP.";


amytis.addEventListener("click", function(){ alert(amytisText); });
alexander.addEventListener("click", function(){ alert(alexanderText); });
archimedes.addEventListener("click", function(){ alert(archimedesText); });
aristotle.addEventListener("click", function(){ alert(aristotleText); });
aspasia.addEventListener("click", function(){ alert(aspasiaText); });
berenice.addEventListener("click", function(){ alert(bereniceText); });
bilkis.addEventListener("click", function(){ alert(bilkisText); });
caesar.addEventListener("click", function(){ alert(caesarText); });
caligula.addEventListener("click", function(){ alert(caligulaText); });
cleopatra.addEventListener("click", function(){ alert(cleopatraText); });
croesus.addEventListener("click", function(){ alert(croesusText); });
darius.addEventListener("click", function(){ alert(dariusText); });
diocletian.addEventListener("click", function(){ alert(diocletianText); });
euclid.addEventListener("click", function(){ alert(euclidText); });
hammurabi.addEventListener("click", function(){ alert(hammurabiText); });
hannibal.addEventListener("click", function(){ alert(hannibalText); });
hatshepsut.addEventListener("click", function(){ alert(hatshepsutText); });
hiram.addEventListener("click", function(){ alert(hiramText); });
hypatia.addEventListener("click", function(){ alert(hypatiaText); });
imhotep.addEventListener("click", function(){ alert(imhotepText); });
justinian.addEventListener("click", function(){ alert(justinianText); });
leonidas.addEventListener("click", function(){ alert(leonidasText); });
maecenas.addEventListener("click", function(){ alert(maecenasText); });
midas.addEventListener("click", function(){ alert(midasText); });
nebuckadnezzar.addEventListener("click", function(){ alert(nebuckadnezzarText); });
nefertiti.addEventListener("click", function(){ alert(nefertitiText); });
nero.addEventListener("click", function(){ alert(neroText); });
pericles.addEventListener("click", function(){ alert(periclesText); });
phidias.addEventListener("click", function(){ alert(phidiasText); });
plato.addEventListener("click", function(){ alert(platoText); });
praxiteles.addEventListener("click", function(){ alert(praxitelesText); });
ptolemy.addEventListener("click", function(){ alert(ptolemyText); });
pythagoras.addEventListener("click", function(){ alert(pythagorasText); });
ramses.addEventListener("click", function(){ alert(ramsesText); });
salomo.addEventListener("click", function(){ alert(salomoText); });
sappho.addEventListener("click", function(){ alert(sapphoText); });
semiramis.addEventListener("click", function(){ alert(semiramisText); });
tomyris.addEventListener("click", function(){ alert(tomyrisText); });
varro.addEventListener("click", function(){ alert(varroText); });
vitruvius.addEventListener("click", function(){ alert(vitruviusText); });
xenophon.addEventListener("click", function(){ alert(xenophonText); });
zenobia.addEventListener("click", function(){ alert(zenobiaText); });

aganice.addEventListener("click", function(){ alert(aganiceText); });
agrippina.addEventListener("click", function(){ alert(agrippinaText); });
arsinoe.addEventListener("click", function(){ alert(arsinoeText); });
cornelia.addEventListener("click", function(){ alert(corneliaText); });
cynisca.addEventListener("click", function(){ alert(cyniscaText); });
enheduanna.addEventListener("click", function(){ alert(enheduannaText); });
eurypyle.addEventListener("click", function(){ alert(eurypyleText); });
gorgo.addEventListener("click", function(){ alert(gorgoText); });
makeda.addEventListener("click", function(){ alert(makedaText); });
nitocris.addEventListener("click", function(){ alert(nitocrisText); });
octavia.addEventListener("click", function(){ alert(octaviaText); });
phryne.addEventListener("click", function(){ alert(phryneText); });
roxana.addEventListener("click", function(){ alert(roxanaText); });
telesilla.addEventListener("click", function(){ alert(telesillaText); });
theano.addEventListener("click", function(){ alert(theanoText); });