coinAndVPForVT = document.getElementById("coinAndVPForVT");
diplomacy = document.getElementById("diplomacy");
doubleResource = document.getElementById("doubleResource");
extraRecource = document.getElementById("extraRecource");
freeWonder = document.getElementById("freeWonder");
get1And6Coin = document.getElementById("get1And6Coin");
get2And9Coin = document.getElementById("get2And9Coin");
mask = document.getElementById("mask");
moneyForBlack = document.getElementById("moneyForBlack");
neighbourVictoryConflict = document.getElementById("neighbourVictoryConflict");
pay = document.getElementById("pay");
payForVictory = document.getElementById("payForVictory");
payForWonder = document.getElementById("payForWonder");
rebateResource = document.getElementById("rebateResource");

coinAndVPForVTText = "The card earns 1 coin for each Victory token present in the player's city at the moment when it is put into play. At the end of the game, this card earns 1 victory point for each Victory token present in the player's city.";
diplomacyText ="The player takes a Diplomacy token. At the end of the current Age, the player discards this token and doesn't take part in the Conflict resolution. The city to the player's left therefore fights against the one to the player's tight. \n\nNote: the effect of Diplomacy tokens changes when using team rules.";
doubleResourceText ="Each turn, the card produces a resource of the player's choice from among those that their city already produces through its brown and gray cards or the initial resource of their board.";
extraRecourceText ="Each turn, the card produces a resource of the player's choice from among those not produced by their city through its brown and gray cards, as well as a possible initial resource from their board.";
freeWonderText ="Starting from the moment this card enters play, the player can build his or her Wonder stages without having to pay their resource costs";
get1And6CoinText ="The player takes 6 coins from the bank. The player's two neighbors each take 1 coin from the bank.";
get2And9CoinText ="The player takes 9 coins from the bank. The player's two neighbors each take 2 coins from the bank.";
maskText ="At the end of the game, the mask copies the scientic symbol of a green card present in one of the two neighboring cities.";
moneyForBlackText ="The card earns 1 coin for each black card present in the player's city at the moment when it is put into play (itself included). At the end of the game, this card earns 1 victory point for each black card present in the player's city (itself included).";
neighbourVictoryConflictText ="The card is worth 1 victory point for each Victory Conict token present in each of the two neighboring cities";
payText ="Each player, other than the one who has put this card in play (or built the Wonder stage), must pay the number of coins indicated to the bank. For each coin the player does not or cannot pay, the player takes a Debt token.";
payForVictoryText ="Each player, other than the one who has put this card in play, must pay 1 coin to the bank for each Victory token in their possession.";
payForWonderText ="Each player, other than the one who has put this card in play, must discard 1 coin for each stage of his or her Wonder that’s already been built";
rebateResourceText ="Each turn, the player has a commercial rebate of one coin on the first resource he or she purchases from the neighboring city (left or right depending on the symbol).";

coinAndVPForVT.addEventListener("click", function(){ alert(coinAndVPForVTText); });
diplomacy.addEventListener("click", function(){ alert(diplomacyText); });
doubleResource.addEventListener("click", function(){ alert(doubleResourceText); });
extraRecource.addEventListener("click", function(){ alert(extraRecourceText); });
freeWonder.addEventListener("click", function(){ alert(freeWonderText); });
get1And6Coin.addEventListener("click", function(){ alert(get1And6CoinText); });
get2And9Coin.addEventListener("click", function(){ alert(get2And9CoinText); });
mask.addEventListener("click", function(){ alert(maskText); });
moneyForBlack.addEventListener("click", function(){ alert(moneyForBlackText); });
neighbourVictoryConflict.addEventListener("click", function(){ alert(neighbourVictoryConflictText); });
pay.addEventListener("click", function(){ alert(payText); });
payForVictory.addEventListener("click", function(){ alert(payForVictoryText); });
payForWonder.addEventListener("click", function(){ alert(payForWonderText); });
rebateResource.addEventListener("click", function(){ alert(rebateResourceText); });